const ENV = {
  STEP: 6,
  PHYSICS_ENGINE_STEPS: 512,
  SPATIAL_GRID_CELL_SIZE: 1000,
  DEFAULT_CANVAS_SIZE: 10000,
  SUPPORTED_SAVE_VERSION: "1.7.0",
  CURRENT_VERSION: "1.16.1",
}

export default ENV;